<?php

	/*
	THIS FILE WAS AUTOMATICALLY GENERATED BY MGB
	DO NOT MODIFY IT!

	DATE FILE WAS CREATED: 02 Feb 2026, 23:26
	*/

	// Database settings
	$db = [
		'hostname' => '10.35.232.188',
		'dbname' => 'k41057_mgb_dev',
		'username' => 'k41057_mgb_dev',
		'password' => 'w@F564x9b',
		'prefix' => 'mgb_'
	];

	$mgb_installation_complete = TRUE;
	$mgb_installation_timestamp = 1770071203;

?>